language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
script:
  - yarn test:ci
before_deploy:
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  edge: true # opt in to dpl v2
  skip_cleanup: true
  local_dir: ./build
branches:
  only:
    - master
