language: node_js
node_js:
  - lts/*
install:
  - yarn install --frozen-lockfile
script:
  - yarn test:ci
  - yarn build
before_deploy:
  - npm install -g serverless@"<4.0.0"
deploy:
  provider: script
  script: sls client deploy --no-confirm --no-config-change --no-policy-change -no-cors-change
  edge: true # opt in to dpl v2
  on:
    tags: true
notifications:
  email:
    enabled: true