language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
before_script:
  # this is a tmp fix for https://github.com/webpack/webpack/issues/14532
  - export NODE_OPTIONS=--openssl-legacy-provider
script:
  - yarn test:ci
  - yarn build
before_deploy:
  - npm install -g serverless
deploy:
  provider: script
  script: sls client deploy --no-confirm --no-config-change --no-policy-change -no-cors-change
  edge: true # opt in to dpl v2
  on:
    tags: true
notifications:
  email:
    enabled: true