language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
script:
  - yarn test:ci
deploy:
  provider: s3
  bucket: covid19-dashboard-20200429
  edge: true # opt in to dpl v2
  region: ap-east-1
  skip_cleanup: true
  local_dir: ./build
branches:
  only:
    - master
